# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mkovoor <mkovoor@student.42.fr>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2022/02/09 14:01:55 by mkovoor           #+#    #+#              #
#    Updated: 2022/06/16 17:23:15 by mkovoor          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC		= gcc
CFLAGS	= -c -Wall -Wextra -Werror
LIB1	= ar -rcs
LIB2	= ranlib
RM		= /bin/rm -f

NAME	= libft.a

INCLUDE	= libft.h

SRCS	= ft_isascii.c ft_isprint.c ft_isalpha.c ft_isdigit.c \
			ft_isalnum.c ft_tolower.c ft_toupper.c ft_memset.c \
			ft_bzero.c ft_memcpy.c ft_memmove.c ft_memchr.c \
			ft_memcmp.c ft_strlen.c ft_strchr.c	ft_strrchr.c \
			ft_strncmp.c ft_strlcpy.c ft_strlcat.c ft_strnstr.c \
			ft_strdup.c ft_atoi.c ft_calloc.c ft_putchar_fd.c \
			ft_putstr_fd.c ft_putnbr_fd.c ft_putendl_fd.c \
			ft_strjoin.c ft_substr.c ft_strtrim.c ft_strmapi.c \
			ft_striteri.c ft_itoa.c ft_split.c ft_printf_char.c \
			ft_printf_d.c ft_printf_p.c ft_printf_s.c \
			ft_printf_u.c ft_printf_x.c ft_printf.c

OBJS	= $(SRCS:.c=.o)

BONUS_S	= ft_lstnew.c ft_lstadd_front.c ft_lstsize.c \
		  ft_lstlast.c ft_lstadd_back.c ft_lstclear.c \
		  ft_lstdelone.c ft_lstiter.c ft_lstmap.c 

BONUS_O	= $(BONUS_S:.c=.o)

all:		$(NAME) 

$(NAME):	$(OBJS) $(INCLUDE)
			$(LIB1) $(NAME) $(OBJS)
			# $(LIB2) $(NAME) 

bonus:		$(NAME) $(BONUS_O)
			$(LIB1) $(NAME) $(BONUS_O)
			# $(LIB2) $(NAME)

.c.o:
			$(CC) $(CFLAGS) -I$(INCLUDE) -c $< -o $(<:.c=.o)

clean:
			$(RM) $(OBJS) $(BONUS_O)

fclean:		clean
			$(RM) $(NAME)

re:			fclean all

rebonus:	fclean bonus

.PHONY:		all clean fclean re bonus rebonus